# Generated by Django 3.1.4 on 2021-05-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitirganlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muvofaqqiyatli', models.PositiveIntegerField(verbose_name='Muvofaqqiyatli bitirganlar')),
                ('sertifikat_olganlar', models.PositiveIntegerField(verbose_name='Sertifikat olganlar')),
            ],
            options={
                'verbose_name': 'Bitirganlar va Sertifikat olganla',
                'verbose_name_plural': 'Bitirganlar va Sertifikat olganla',
            },
        ),
        migrations.CreateModel(
            name='Bolim_izox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galareya', models.CharField(max_length=100)),
                ('oqituvchi', models.CharField(max_length=100)),
                ('tadbirlar', models.CharField(max_length=100)),
                ('murojaat', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Bo'limlarga izoxlar",
                'verbose_name_plural': "Bo'limlarga izoxlar",
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasm', models.ImageField(upload_to='events')),
                ('izox', models.TextField()),
                ('sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Galareya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasm', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Haqimizda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='haqimizda')),
                ('qisqa', models.CharField(max_length=100)),
                ('toliq', models.TextField()),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
            },
        ),
        migrations.CreateModel(
            name='malumot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('toliq', models.TextField()),
                ('rasm', models.ImageField(upload_to='malumotlar_rasm')),
            ],
            options={
                'verbose_name': "O'quv markaz haqida ma'lumot",
                'verbose_name_plural': "O'quv markaz haqida ma'lumotlar",
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='slider_rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Tarmoq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarmoq_nomi', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tarmoq_icon')),
                ('url', models.URLField(verbose_name='Ijtimoiy tarmoqdagi sahifani usernamei')),
            ],
        ),
        migrations.CreateModel(
            name='MalumotQoldirish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=17)),
                ('toliq', models.TextField()),
                ('manzil', models.CharField(max_length=300)),
                ('qayerdan_keldi', models.CharField(max_length=50)),
                ('toifa', models.CharField(default='Qayta aloqaga chiqmagan', max_length=50)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('dars', models.ManyToManyField(blank=True, null=True, to='dashboard.Fan')),
            ],
            options={
                'verbose_name_plural': 'Murojatlar',
            },
        ),
    ]
